// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JoinTree.proto
package tree;

public final class ProtobufJoinTree {
  private ProtobufJoinTree() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TripleOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .Triple.Element subject = 1;
    /**
     * <code>required .Triple.Element subject = 1;</code>
     */
    boolean hasSubject();
    /**
     * <code>required .Triple.Element subject = 1;</code>
     */
    ProtobufJoinTree.Triple.Element getSubject();
    /**
     * <code>required .Triple.Element subject = 1;</code>
     */
    ProtobufJoinTree.Triple.ElementOrBuilder getSubjectOrBuilder();

    // required .Triple.Element predicate = 2;
    /**
     * <code>required .Triple.Element predicate = 2;</code>
     */
    boolean hasPredicate();
    /**
     * <code>required .Triple.Element predicate = 2;</code>
     */
    ProtobufJoinTree.Triple.Element getPredicate();
    /**
     * <code>required .Triple.Element predicate = 2;</code>
     */
    ProtobufJoinTree.Triple.ElementOrBuilder getPredicateOrBuilder();

    // required .Triple.Element object = 3;
    /**
     * <code>required .Triple.Element object = 3;</code>
     */
    boolean hasObject();
    /**
     * <code>required .Triple.Element object = 3;</code>
     */
    ProtobufJoinTree.Triple.Element getObject();
    /**
     * <code>required .Triple.Element object = 3;</code>
     */
    ProtobufJoinTree.Triple.ElementOrBuilder getObjectOrBuilder();

    // optional .Table stats = 4;
    /**
     * <code>optional .Table stats = 4;</code>
     */
    boolean hasStats();
    /**
     * <code>optional .Table stats = 4;</code>
     */
    ProtobufStats.Table getStats();
    /**
     * <code>optional .Table stats = 4;</code>
     */
    ProtobufStats.TableOrBuilder getStatsOrBuilder();
  }
  /**
   * Protobuf type {@code Triple}
   */
  public static final class Triple extends
      com.google.protobuf.GeneratedMessage
      implements TripleOrBuilder {
    // Use Triple.newBuilder() to construct.
    private Triple(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Triple(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Triple defaultInstance;
    public static Triple getDefaultInstance() {
      return defaultInstance;
    }

    public Triple getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Triple(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ProtobufJoinTree.Triple.Element.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = subject_.toBuilder();
              }
              subject_ = input.readMessage(ProtobufJoinTree.Triple.Element.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(subject_);
                subject_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              ProtobufJoinTree.Triple.Element.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = predicate_.toBuilder();
              }
              predicate_ = input.readMessage(ProtobufJoinTree.Triple.Element.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(predicate_);
                predicate_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              ProtobufJoinTree.Triple.Element.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = object_.toBuilder();
              }
              object_ = input.readMessage(ProtobufJoinTree.Triple.Element.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(object_);
                object_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              ProtobufStats.Table.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = stats_.toBuilder();
              }
              stats_ = input.readMessage(ProtobufStats.Table.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(stats_);
                stats_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtobufJoinTree.internal_static_Triple_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtobufJoinTree.internal_static_Triple_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtobufJoinTree.Triple.class, ProtobufJoinTree.Triple.Builder.class);
    }

    public static com.google.protobuf.Parser<Triple> PARSER =
        new com.google.protobuf.AbstractParser<Triple>() {
      public Triple parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Triple(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Triple> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Triple.ElementType}
     */
    public enum ElementType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>VARIABLE = 0;</code>
       */
      VARIABLE(0, 0),
      /**
       * <code>CONSTANT = 1;</code>
       */
      CONSTANT(1, 1),
      ;

      /**
       * <code>VARIABLE = 0;</code>
       */
      public static final int VARIABLE_VALUE = 0;
      /**
       * <code>CONSTANT = 1;</code>
       */
      public static final int CONSTANT_VALUE = 1;


      public final int getNumber() { return value; }

      public static ElementType valueOf(int value) {
        switch (value) {
          case 0: return VARIABLE;
          case 1: return CONSTANT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ElementType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ElementType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ElementType>() {
              public ElementType findValueByNumber(int number) {
                return ElementType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ProtobufJoinTree.Triple.getDescriptor().getEnumTypes().get(0);
      }

      private static final ElementType[] VALUES = values();

      public static ElementType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ElementType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Triple.ElementType)
    }

    public interface ElementOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string name = 1;
      /**
       * <code>required string name = 1;</code>
       */
      boolean hasName();
      /**
       * <code>required string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>required string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      // required .Triple.ElementType type = 2;
      /**
       * <code>required .Triple.ElementType type = 2;</code>
       */
      boolean hasType();
      /**
       * <code>required .Triple.ElementType type = 2;</code>
       */
      ProtobufJoinTree.Triple.ElementType getType();
    }
    /**
     * Protobuf type {@code Triple.Element}
     */
    public static final class Element extends
        com.google.protobuf.GeneratedMessage
        implements ElementOrBuilder {
      // Use Element.newBuilder() to construct.
      private Element(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Element(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Element defaultInstance;
      public static Element getDefaultInstance() {
        return defaultInstance;
      }

      public Element getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Element(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                ProtobufJoinTree.Triple.ElementType value = ProtobufJoinTree.Triple.ElementType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000002;
                  type_ = value;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtobufJoinTree.internal_static_Triple_Element_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtobufJoinTree.internal_static_Triple_Element_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtobufJoinTree.Triple.Element.class, ProtobufJoinTree.Triple.Element.Builder.class);
      }

      public static com.google.protobuf.Parser<Element> PARSER =
          new com.google.protobuf.AbstractParser<Element>() {
        public Element parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Element(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Element> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required .Triple.ElementType type = 2;
      public static final int TYPE_FIELD_NUMBER = 2;
      private ProtobufJoinTree.Triple.ElementType type_;
      /**
       * <code>required .Triple.ElementType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .Triple.ElementType type = 2;</code>
       */
      public ProtobufJoinTree.Triple.ElementType getType() {
        return type_;
      }

      private void initFields() {
        name_ = "";
        type_ = ProtobufJoinTree.Triple.ElementType.VARIABLE;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, type_.getNumber());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_.getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static ProtobufJoinTree.Triple.Element parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtobufJoinTree.Triple.Element parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtobufJoinTree.Triple.Element parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtobufJoinTree.Triple.Element parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtobufJoinTree.Triple.Element parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static ProtobufJoinTree.Triple.Element parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static ProtobufJoinTree.Triple.Element parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static ProtobufJoinTree.Triple.Element parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static ProtobufJoinTree.Triple.Element parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static ProtobufJoinTree.Triple.Element parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(ProtobufJoinTree.Triple.Element prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Triple.Element}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements ProtobufJoinTree.Triple.ElementOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ProtobufJoinTree.internal_static_Triple_Element_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ProtobufJoinTree.internal_static_Triple_Element_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ProtobufJoinTree.Triple.Element.class, ProtobufJoinTree.Triple.Element.Builder.class);
        }

        // Construct using JoinTree.Triple.Element.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = ProtobufJoinTree.Triple.ElementType.VARIABLE;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ProtobufJoinTree.internal_static_Triple_Element_descriptor;
        }

        public ProtobufJoinTree.Triple.Element getDefaultInstanceForType() {
          return ProtobufJoinTree.Triple.Element.getDefaultInstance();
        }

        public ProtobufJoinTree.Triple.Element build() {
          ProtobufJoinTree.Triple.Element result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public ProtobufJoinTree.Triple.Element buildPartial() {
          ProtobufJoinTree.Triple.Element result = new ProtobufJoinTree.Triple.Element(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.type_ = type_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ProtobufJoinTree.Triple.Element) {
            return mergeFrom((ProtobufJoinTree.Triple.Element)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ProtobufJoinTree.Triple.Element other) {
          if (other == ProtobufJoinTree.Triple.Element.getDefaultInstance()) return this;
          if (other.hasName()) {
            bitField0_ |= 0x00000001;
            name_ = other.name_;
            onChanged();
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          if (!hasType()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ProtobufJoinTree.Triple.Element parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ProtobufJoinTree.Triple.Element) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string name = 1;
        private java.lang.Object name_ = "";
        /**
         * <code>required string name = 1;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }

        // required .Triple.ElementType type = 2;
        private ProtobufJoinTree.Triple.ElementType type_ = ProtobufJoinTree.Triple.ElementType.VARIABLE;
        /**
         * <code>required .Triple.ElementType type = 2;</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required .Triple.ElementType type = 2;</code>
         */
        public ProtobufJoinTree.Triple.ElementType getType() {
          return type_;
        }
        /**
         * <code>required .Triple.ElementType type = 2;</code>
         */
        public Builder setType(ProtobufJoinTree.Triple.ElementType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required .Triple.ElementType type = 2;</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = ProtobufJoinTree.Triple.ElementType.VARIABLE;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Triple.Element)
      }

      static {
        defaultInstance = new Element(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Triple.Element)
    }

    private int bitField0_;
    // required .Triple.Element subject = 1;
    public static final int SUBJECT_FIELD_NUMBER = 1;
    private ProtobufJoinTree.Triple.Element subject_;
    /**
     * <code>required .Triple.Element subject = 1;</code>
     */
    public boolean hasSubject() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Triple.Element subject = 1;</code>
     */
    public ProtobufJoinTree.Triple.Element getSubject() {
      return subject_;
    }
    /**
     * <code>required .Triple.Element subject = 1;</code>
     */
    public ProtobufJoinTree.Triple.ElementOrBuilder getSubjectOrBuilder() {
      return subject_;
    }

    // required .Triple.Element predicate = 2;
    public static final int PREDICATE_FIELD_NUMBER = 2;
    private ProtobufJoinTree.Triple.Element predicate_;
    /**
     * <code>required .Triple.Element predicate = 2;</code>
     */
    public boolean hasPredicate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .Triple.Element predicate = 2;</code>
     */
    public ProtobufJoinTree.Triple.Element getPredicate() {
      return predicate_;
    }
    /**
     * <code>required .Triple.Element predicate = 2;</code>
     */
    public ProtobufJoinTree.Triple.ElementOrBuilder getPredicateOrBuilder() {
      return predicate_;
    }

    // required .Triple.Element object = 3;
    public static final int OBJECT_FIELD_NUMBER = 3;
    private ProtobufJoinTree.Triple.Element object_;
    /**
     * <code>required .Triple.Element object = 3;</code>
     */
    public boolean hasObject() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .Triple.Element object = 3;</code>
     */
    public ProtobufJoinTree.Triple.Element getObject() {
      return object_;
    }
    /**
     * <code>required .Triple.Element object = 3;</code>
     */
    public ProtobufJoinTree.Triple.ElementOrBuilder getObjectOrBuilder() {
      return object_;
    }

    // optional .Table stats = 4;
    public static final int STATS_FIELD_NUMBER = 4;
    private ProtobufStats.Table stats_;
    /**
     * <code>optional .Table stats = 4;</code>
     */
    public boolean hasStats() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .Table stats = 4;</code>
     */
    public ProtobufStats.Table getStats() {
      return stats_;
    }
    /**
     * <code>optional .Table stats = 4;</code>
     */
    public ProtobufStats.TableOrBuilder getStatsOrBuilder() {
      return stats_;
    }

    private void initFields() {
      subject_ = ProtobufJoinTree.Triple.Element.getDefaultInstance();
      predicate_ = ProtobufJoinTree.Triple.Element.getDefaultInstance();
      object_ = ProtobufJoinTree.Triple.Element.getDefaultInstance();
      stats_ = ProtobufStats.Table.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSubject()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPredicate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasObject()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSubject().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getPredicate().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getObject().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasStats()) {
        if (!getStats().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, subject_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, predicate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, object_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, stats_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, subject_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, predicate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, object_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, stats_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ProtobufJoinTree.Triple parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtobufJoinTree.Triple parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtobufJoinTree.Triple parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtobufJoinTree.Triple parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtobufJoinTree.Triple parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtobufJoinTree.Triple parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProtobufJoinTree.Triple parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProtobufJoinTree.Triple parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProtobufJoinTree.Triple parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtobufJoinTree.Triple parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtobufJoinTree.Triple prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Triple}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtobufJoinTree.TripleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtobufJoinTree.internal_static_Triple_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtobufJoinTree.internal_static_Triple_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtobufJoinTree.Triple.class, ProtobufJoinTree.Triple.Builder.class);
      }

      // Construct using JoinTree.Triple.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSubjectFieldBuilder();
          getPredicateFieldBuilder();
          getObjectFieldBuilder();
          getStatsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (subjectBuilder_ == null) {
          subject_ = ProtobufJoinTree.Triple.Element.getDefaultInstance();
        } else {
          subjectBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (predicateBuilder_ == null) {
          predicate_ = ProtobufJoinTree.Triple.Element.getDefaultInstance();
        } else {
          predicateBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (objectBuilder_ == null) {
          object_ = ProtobufJoinTree.Triple.Element.getDefaultInstance();
        } else {
          objectBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (statsBuilder_ == null) {
          stats_ = ProtobufStats.Table.getDefaultInstance();
        } else {
          statsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtobufJoinTree.internal_static_Triple_descriptor;
      }

      public ProtobufJoinTree.Triple getDefaultInstanceForType() {
        return ProtobufJoinTree.Triple.getDefaultInstance();
      }

      public ProtobufJoinTree.Triple build() {
        ProtobufJoinTree.Triple result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtobufJoinTree.Triple buildPartial() {
        ProtobufJoinTree.Triple result = new ProtobufJoinTree.Triple(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (subjectBuilder_ == null) {
          result.subject_ = subject_;
        } else {
          result.subject_ = subjectBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (predicateBuilder_ == null) {
          result.predicate_ = predicate_;
        } else {
          result.predicate_ = predicateBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (objectBuilder_ == null) {
          result.object_ = object_;
        } else {
          result.object_ = objectBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (statsBuilder_ == null) {
          result.stats_ = stats_;
        } else {
          result.stats_ = statsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtobufJoinTree.Triple) {
          return mergeFrom((ProtobufJoinTree.Triple)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtobufJoinTree.Triple other) {
        if (other == ProtobufJoinTree.Triple.getDefaultInstance()) return this;
        if (other.hasSubject()) {
          mergeSubject(other.getSubject());
        }
        if (other.hasPredicate()) {
          mergePredicate(other.getPredicate());
        }
        if (other.hasObject()) {
          mergeObject(other.getObject());
        }
        if (other.hasStats()) {
          mergeStats(other.getStats());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSubject()) {
          
          return false;
        }
        if (!hasPredicate()) {
          
          return false;
        }
        if (!hasObject()) {
          
          return false;
        }
        if (!getSubject().isInitialized()) {
          
          return false;
        }
        if (!getPredicate().isInitialized()) {
          
          return false;
        }
        if (!getObject().isInitialized()) {
          
          return false;
        }
        if (hasStats()) {
          if (!getStats().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtobufJoinTree.Triple parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtobufJoinTree.Triple) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .Triple.Element subject = 1;
      private ProtobufJoinTree.Triple.Element subject_ = ProtobufJoinTree.Triple.Element.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ProtobufJoinTree.Triple.Element, ProtobufJoinTree.Triple.Element.Builder, ProtobufJoinTree.Triple.ElementOrBuilder> subjectBuilder_;
      /**
       * <code>required .Triple.Element subject = 1;</code>
       */
      public boolean hasSubject() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Triple.Element subject = 1;</code>
       */
      public ProtobufJoinTree.Triple.Element getSubject() {
        if (subjectBuilder_ == null) {
          return subject_;
        } else {
          return subjectBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Triple.Element subject = 1;</code>
       */
      public Builder setSubject(ProtobufJoinTree.Triple.Element value) {
        if (subjectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          subject_ = value;
          onChanged();
        } else {
          subjectBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Triple.Element subject = 1;</code>
       */
      public Builder setSubject(
          ProtobufJoinTree.Triple.Element.Builder builderForValue) {
        if (subjectBuilder_ == null) {
          subject_ = builderForValue.build();
          onChanged();
        } else {
          subjectBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Triple.Element subject = 1;</code>
       */
      public Builder mergeSubject(ProtobufJoinTree.Triple.Element value) {
        if (subjectBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              subject_ != ProtobufJoinTree.Triple.Element.getDefaultInstance()) {
            subject_ =
              ProtobufJoinTree.Triple.Element.newBuilder(subject_).mergeFrom(value).buildPartial();
          } else {
            subject_ = value;
          }
          onChanged();
        } else {
          subjectBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Triple.Element subject = 1;</code>
       */
      public Builder clearSubject() {
        if (subjectBuilder_ == null) {
          subject_ = ProtobufJoinTree.Triple.Element.getDefaultInstance();
          onChanged();
        } else {
          subjectBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .Triple.Element subject = 1;</code>
       */
      public ProtobufJoinTree.Triple.Element.Builder getSubjectBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSubjectFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Triple.Element subject = 1;</code>
       */
      public ProtobufJoinTree.Triple.ElementOrBuilder getSubjectOrBuilder() {
        if (subjectBuilder_ != null) {
          return subjectBuilder_.getMessageOrBuilder();
        } else {
          return subject_;
        }
      }
      /**
       * <code>required .Triple.Element subject = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ProtobufJoinTree.Triple.Element, ProtobufJoinTree.Triple.Element.Builder, ProtobufJoinTree.Triple.ElementOrBuilder> 
          getSubjectFieldBuilder() {
        if (subjectBuilder_ == null) {
          subjectBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ProtobufJoinTree.Triple.Element, ProtobufJoinTree.Triple.Element.Builder, ProtobufJoinTree.Triple.ElementOrBuilder>(
                  subject_,
                  getParentForChildren(),
                  isClean());
          subject_ = null;
        }
        return subjectBuilder_;
      }

      // required .Triple.Element predicate = 2;
      private ProtobufJoinTree.Triple.Element predicate_ = ProtobufJoinTree.Triple.Element.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ProtobufJoinTree.Triple.Element, ProtobufJoinTree.Triple.Element.Builder, ProtobufJoinTree.Triple.ElementOrBuilder> predicateBuilder_;
      /**
       * <code>required .Triple.Element predicate = 2;</code>
       */
      public boolean hasPredicate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .Triple.Element predicate = 2;</code>
       */
      public ProtobufJoinTree.Triple.Element getPredicate() {
        if (predicateBuilder_ == null) {
          return predicate_;
        } else {
          return predicateBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Triple.Element predicate = 2;</code>
       */
      public Builder setPredicate(ProtobufJoinTree.Triple.Element value) {
        if (predicateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          predicate_ = value;
          onChanged();
        } else {
          predicateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Triple.Element predicate = 2;</code>
       */
      public Builder setPredicate(
          ProtobufJoinTree.Triple.Element.Builder builderForValue) {
        if (predicateBuilder_ == null) {
          predicate_ = builderForValue.build();
          onChanged();
        } else {
          predicateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Triple.Element predicate = 2;</code>
       */
      public Builder mergePredicate(ProtobufJoinTree.Triple.Element value) {
        if (predicateBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              predicate_ != ProtobufJoinTree.Triple.Element.getDefaultInstance()) {
            predicate_ =
              ProtobufJoinTree.Triple.Element.newBuilder(predicate_).mergeFrom(value).buildPartial();
          } else {
            predicate_ = value;
          }
          onChanged();
        } else {
          predicateBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Triple.Element predicate = 2;</code>
       */
      public Builder clearPredicate() {
        if (predicateBuilder_ == null) {
          predicate_ = ProtobufJoinTree.Triple.Element.getDefaultInstance();
          onChanged();
        } else {
          predicateBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .Triple.Element predicate = 2;</code>
       */
      public ProtobufJoinTree.Triple.Element.Builder getPredicateBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPredicateFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Triple.Element predicate = 2;</code>
       */
      public ProtobufJoinTree.Triple.ElementOrBuilder getPredicateOrBuilder() {
        if (predicateBuilder_ != null) {
          return predicateBuilder_.getMessageOrBuilder();
        } else {
          return predicate_;
        }
      }
      /**
       * <code>required .Triple.Element predicate = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ProtobufJoinTree.Triple.Element, ProtobufJoinTree.Triple.Element.Builder, ProtobufJoinTree.Triple.ElementOrBuilder> 
          getPredicateFieldBuilder() {
        if (predicateBuilder_ == null) {
          predicateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ProtobufJoinTree.Triple.Element, ProtobufJoinTree.Triple.Element.Builder, ProtobufJoinTree.Triple.ElementOrBuilder>(
                  predicate_,
                  getParentForChildren(),
                  isClean());
          predicate_ = null;
        }
        return predicateBuilder_;
      }

      // required .Triple.Element object = 3;
      private ProtobufJoinTree.Triple.Element object_ = ProtobufJoinTree.Triple.Element.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ProtobufJoinTree.Triple.Element, ProtobufJoinTree.Triple.Element.Builder, ProtobufJoinTree.Triple.ElementOrBuilder> objectBuilder_;
      /**
       * <code>required .Triple.Element object = 3;</code>
       */
      public boolean hasObject() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .Triple.Element object = 3;</code>
       */
      public ProtobufJoinTree.Triple.Element getObject() {
        if (objectBuilder_ == null) {
          return object_;
        } else {
          return objectBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Triple.Element object = 3;</code>
       */
      public Builder setObject(ProtobufJoinTree.Triple.Element value) {
        if (objectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          object_ = value;
          onChanged();
        } else {
          objectBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .Triple.Element object = 3;</code>
       */
      public Builder setObject(
          ProtobufJoinTree.Triple.Element.Builder builderForValue) {
        if (objectBuilder_ == null) {
          object_ = builderForValue.build();
          onChanged();
        } else {
          objectBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .Triple.Element object = 3;</code>
       */
      public Builder mergeObject(ProtobufJoinTree.Triple.Element value) {
        if (objectBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              object_ != ProtobufJoinTree.Triple.Element.getDefaultInstance()) {
            object_ =
              ProtobufJoinTree.Triple.Element.newBuilder(object_).mergeFrom(value).buildPartial();
          } else {
            object_ = value;
          }
          onChanged();
        } else {
          objectBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .Triple.Element object = 3;</code>
       */
      public Builder clearObject() {
        if (objectBuilder_ == null) {
          object_ = ProtobufJoinTree.Triple.Element.getDefaultInstance();
          onChanged();
        } else {
          objectBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .Triple.Element object = 3;</code>
       */
      public ProtobufJoinTree.Triple.Element.Builder getObjectBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getObjectFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Triple.Element object = 3;</code>
       */
      public ProtobufJoinTree.Triple.ElementOrBuilder getObjectOrBuilder() {
        if (objectBuilder_ != null) {
          return objectBuilder_.getMessageOrBuilder();
        } else {
          return object_;
        }
      }
      /**
       * <code>required .Triple.Element object = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ProtobufJoinTree.Triple.Element, ProtobufJoinTree.Triple.Element.Builder, ProtobufJoinTree.Triple.ElementOrBuilder> 
          getObjectFieldBuilder() {
        if (objectBuilder_ == null) {
          objectBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ProtobufJoinTree.Triple.Element, ProtobufJoinTree.Triple.Element.Builder, ProtobufJoinTree.Triple.ElementOrBuilder>(
                  object_,
                  getParentForChildren(),
                  isClean());
          object_ = null;
        }
        return objectBuilder_;
      }

      // optional .Table stats = 4;
      private ProtobufStats.Table stats_ = ProtobufStats.Table.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ProtobufStats.Table, ProtobufStats.Table.Builder, ProtobufStats.TableOrBuilder> statsBuilder_;
      /**
       * <code>optional .Table stats = 4;</code>
       */
      public boolean hasStats() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .Table stats = 4;</code>
       */
      public ProtobufStats.Table getStats() {
        if (statsBuilder_ == null) {
          return stats_;
        } else {
          return statsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Table stats = 4;</code>
       */
      public Builder setStats(ProtobufStats.Table value) {
        if (statsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          stats_ = value;
          onChanged();
        } else {
          statsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Table stats = 4;</code>
       */
      public Builder setStats(
          ProtobufStats.Table.Builder builderForValue) {
        if (statsBuilder_ == null) {
          stats_ = builderForValue.build();
          onChanged();
        } else {
          statsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Table stats = 4;</code>
       */
      public Builder mergeStats(ProtobufStats.Table value) {
        if (statsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              stats_ != ProtobufStats.Table.getDefaultInstance()) {
            stats_ =
              ProtobufStats.Table.newBuilder(stats_).mergeFrom(value).buildPartial();
          } else {
            stats_ = value;
          }
          onChanged();
        } else {
          statsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Table stats = 4;</code>
       */
      public Builder clearStats() {
        if (statsBuilder_ == null) {
          stats_ = ProtobufStats.Table.getDefaultInstance();
          onChanged();
        } else {
          statsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .Table stats = 4;</code>
       */
      public ProtobufStats.Table.Builder getStatsBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getStatsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Table stats = 4;</code>
       */
      public ProtobufStats.TableOrBuilder getStatsOrBuilder() {
        if (statsBuilder_ != null) {
          return statsBuilder_.getMessageOrBuilder();
        } else {
          return stats_;
        }
      }
      /**
       * <code>optional .Table stats = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ProtobufStats.Table, ProtobufStats.Table.Builder, ProtobufStats.TableOrBuilder> 
          getStatsFieldBuilder() {
        if (statsBuilder_ == null) {
          statsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ProtobufStats.Table, ProtobufStats.Table.Builder, ProtobufStats.TableOrBuilder>(
                  stats_,
                  getParentForChildren(),
                  isClean());
          stats_ = null;
        }
        return statsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Triple)
    }

    static {
      defaultInstance = new Triple(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Triple)
  }

  public interface NodeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .Triple triple = 1;
    /**
     * <code>required .Triple triple = 1;</code>
     */
    boolean hasTriple();
    /**
     * <code>required .Triple triple = 1;</code>
     */
    ProtobufJoinTree.Triple getTriple();
    /**
     * <code>required .Triple triple = 1;</code>
     */
    ProtobufJoinTree.TripleOrBuilder getTripleOrBuilder();

    // repeated .Node children = 2;
    /**
     * <code>repeated .Node children = 2;</code>
     */
    java.util.List<ProtobufJoinTree.Node> 
        getChildrenList();
    /**
     * <code>repeated .Node children = 2;</code>
     */
    ProtobufJoinTree.Node getChildren(int index);
    /**
     * <code>repeated .Node children = 2;</code>
     */
    int getChildrenCount();
    /**
     * <code>repeated .Node children = 2;</code>
     */
    java.util.List<? extends ProtobufJoinTree.NodeOrBuilder> 
        getChildrenOrBuilderList();
    /**
     * <code>repeated .Node children = 2;</code>
     */
    ProtobufJoinTree.NodeOrBuilder getChildrenOrBuilder(
        int index);

    // repeated string projection = 3;
    /**
     * <code>repeated string projection = 3;</code>
     */
    java.util.List<java.lang.String>
    getProjectionList();
    /**
     * <code>repeated string projection = 3;</code>
     */
    int getProjectionCount();
    /**
     * <code>repeated string projection = 3;</code>
     */
    java.lang.String getProjection(int index);
    /**
     * <code>repeated string projection = 3;</code>
     */
    com.google.protobuf.ByteString
        getProjectionBytes(int index);
  }
  /**
   * Protobuf type {@code Node}
   */
  public static final class Node extends
      com.google.protobuf.GeneratedMessage
      implements NodeOrBuilder {
    // Use Node.newBuilder() to construct.
    private Node(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Node(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Node defaultInstance;
    public static Node getDefaultInstance() {
      return defaultInstance;
    }

    public Node getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Node(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ProtobufJoinTree.Triple.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = triple_.toBuilder();
              }
              triple_ = input.readMessage(ProtobufJoinTree.Triple.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(triple_);
                triple_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                children_ = new java.util.ArrayList<ProtobufJoinTree.Node>();
                mutable_bitField0_ |= 0x00000002;
              }
              children_.add(input.readMessage(ProtobufJoinTree.Node.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                projection_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              projection_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          children_ = java.util.Collections.unmodifiableList(children_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          projection_ = new com.google.protobuf.UnmodifiableLazyStringList(projection_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtobufJoinTree.internal_static_Node_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtobufJoinTree.internal_static_Node_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtobufJoinTree.Node.class, ProtobufJoinTree.Node.Builder.class);
    }

    public static com.google.protobuf.Parser<Node> PARSER =
        new com.google.protobuf.AbstractParser<Node>() {
      public Node parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Node(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Node> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .Triple triple = 1;
    public static final int TRIPLE_FIELD_NUMBER = 1;
    private ProtobufJoinTree.Triple triple_;
    /**
     * <code>required .Triple triple = 1;</code>
     */
    public boolean hasTriple() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Triple triple = 1;</code>
     */
    public ProtobufJoinTree.Triple getTriple() {
      return triple_;
    }
    /**
     * <code>required .Triple triple = 1;</code>
     */
    public ProtobufJoinTree.TripleOrBuilder getTripleOrBuilder() {
      return triple_;
    }

    // repeated .Node children = 2;
    public static final int CHILDREN_FIELD_NUMBER = 2;
    private java.util.List<ProtobufJoinTree.Node> children_;
    /**
     * <code>repeated .Node children = 2;</code>
     */
    public java.util.List<ProtobufJoinTree.Node> getChildrenList() {
      return children_;
    }
    /**
     * <code>repeated .Node children = 2;</code>
     */
    public java.util.List<? extends ProtobufJoinTree.NodeOrBuilder> 
        getChildrenOrBuilderList() {
      return children_;
    }
    /**
     * <code>repeated .Node children = 2;</code>
     */
    public int getChildrenCount() {
      return children_.size();
    }
    /**
     * <code>repeated .Node children = 2;</code>
     */
    public ProtobufJoinTree.Node getChildren(int index) {
      return children_.get(index);
    }
    /**
     * <code>repeated .Node children = 2;</code>
     */
    public ProtobufJoinTree.NodeOrBuilder getChildrenOrBuilder(
        int index) {
      return children_.get(index);
    }

    // repeated string projection = 3;
    public static final int PROJECTION_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList projection_;
    /**
     * <code>repeated string projection = 3;</code>
     */
    public java.util.List<java.lang.String>
        getProjectionList() {
      return projection_;
    }
    /**
     * <code>repeated string projection = 3;</code>
     */
    public int getProjectionCount() {
      return projection_.size();
    }
    /**
     * <code>repeated string projection = 3;</code>
     */
    public java.lang.String getProjection(int index) {
      return projection_.get(index);
    }
    /**
     * <code>repeated string projection = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProjectionBytes(int index) {
      return projection_.getByteString(index);
    }

    private void initFields() {
      triple_ = ProtobufJoinTree.Triple.getDefaultInstance();
      children_ = java.util.Collections.emptyList();
      projection_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTriple()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getTriple().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getChildrenCount(); i++) {
        if (!getChildren(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, triple_);
      }
      for (int i = 0; i < children_.size(); i++) {
        output.writeMessage(2, children_.get(i));
      }
      for (int i = 0; i < projection_.size(); i++) {
        output.writeBytes(3, projection_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, triple_);
      }
      for (int i = 0; i < children_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, children_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < projection_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(projection_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getProjectionList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ProtobufJoinTree.Node parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtobufJoinTree.Node parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtobufJoinTree.Node parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtobufJoinTree.Node parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtobufJoinTree.Node parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtobufJoinTree.Node parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProtobufJoinTree.Node parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProtobufJoinTree.Node parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProtobufJoinTree.Node parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtobufJoinTree.Node parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtobufJoinTree.Node prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Node}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtobufJoinTree.NodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtobufJoinTree.internal_static_Node_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtobufJoinTree.internal_static_Node_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtobufJoinTree.Node.class, ProtobufJoinTree.Node.Builder.class);
      }

      // Construct using JoinTree.Node.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTripleFieldBuilder();
          getChildrenFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (tripleBuilder_ == null) {
          triple_ = ProtobufJoinTree.Triple.getDefaultInstance();
        } else {
          tripleBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (childrenBuilder_ == null) {
          children_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          childrenBuilder_.clear();
        }
        projection_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtobufJoinTree.internal_static_Node_descriptor;
      }

      public ProtobufJoinTree.Node getDefaultInstanceForType() {
        return ProtobufJoinTree.Node.getDefaultInstance();
      }

      public ProtobufJoinTree.Node build() {
        ProtobufJoinTree.Node result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtobufJoinTree.Node buildPartial() {
        ProtobufJoinTree.Node result = new ProtobufJoinTree.Node(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (tripleBuilder_ == null) {
          result.triple_ = triple_;
        } else {
          result.triple_ = tripleBuilder_.build();
        }
        if (childrenBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            children_ = java.util.Collections.unmodifiableList(children_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.children_ = children_;
        } else {
          result.children_ = childrenBuilder_.build();
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          projection_ = new com.google.protobuf.UnmodifiableLazyStringList(
              projection_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.projection_ = projection_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtobufJoinTree.Node) {
          return mergeFrom((ProtobufJoinTree.Node)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtobufJoinTree.Node other) {
        if (other == ProtobufJoinTree.Node.getDefaultInstance()) return this;
        if (other.hasTriple()) {
          mergeTriple(other.getTriple());
        }
        if (childrenBuilder_ == null) {
          if (!other.children_.isEmpty()) {
            if (children_.isEmpty()) {
              children_ = other.children_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureChildrenIsMutable();
              children_.addAll(other.children_);
            }
            onChanged();
          }
        } else {
          if (!other.children_.isEmpty()) {
            if (childrenBuilder_.isEmpty()) {
              childrenBuilder_.dispose();
              childrenBuilder_ = null;
              children_ = other.children_;
              bitField0_ = (bitField0_ & ~0x00000002);
              childrenBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getChildrenFieldBuilder() : null;
            } else {
              childrenBuilder_.addAllMessages(other.children_);
            }
          }
        }
        if (!other.projection_.isEmpty()) {
          if (projection_.isEmpty()) {
            projection_ = other.projection_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureProjectionIsMutable();
            projection_.addAll(other.projection_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTriple()) {
          
          return false;
        }
        if (!getTriple().isInitialized()) {
          
          return false;
        }
        for (int i = 0; i < getChildrenCount(); i++) {
          if (!getChildren(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtobufJoinTree.Node parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtobufJoinTree.Node) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .Triple triple = 1;
      private ProtobufJoinTree.Triple triple_ = ProtobufJoinTree.Triple.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ProtobufJoinTree.Triple, ProtobufJoinTree.Triple.Builder, ProtobufJoinTree.TripleOrBuilder> tripleBuilder_;
      /**
       * <code>required .Triple triple = 1;</code>
       */
      public boolean hasTriple() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Triple triple = 1;</code>
       */
      public ProtobufJoinTree.Triple getTriple() {
        if (tripleBuilder_ == null) {
          return triple_;
        } else {
          return tripleBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Triple triple = 1;</code>
       */
      public Builder setTriple(ProtobufJoinTree.Triple value) {
        if (tripleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          triple_ = value;
          onChanged();
        } else {
          tripleBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Triple triple = 1;</code>
       */
      public Builder setTriple(
          ProtobufJoinTree.Triple.Builder builderForValue) {
        if (tripleBuilder_ == null) {
          triple_ = builderForValue.build();
          onChanged();
        } else {
          tripleBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Triple triple = 1;</code>
       */
      public Builder mergeTriple(ProtobufJoinTree.Triple value) {
        if (tripleBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              triple_ != ProtobufJoinTree.Triple.getDefaultInstance()) {
            triple_ =
              ProtobufJoinTree.Triple.newBuilder(triple_).mergeFrom(value).buildPartial();
          } else {
            triple_ = value;
          }
          onChanged();
        } else {
          tripleBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Triple triple = 1;</code>
       */
      public Builder clearTriple() {
        if (tripleBuilder_ == null) {
          triple_ = ProtobufJoinTree.Triple.getDefaultInstance();
          onChanged();
        } else {
          tripleBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .Triple triple = 1;</code>
       */
      public ProtobufJoinTree.Triple.Builder getTripleBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTripleFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Triple triple = 1;</code>
       */
      public ProtobufJoinTree.TripleOrBuilder getTripleOrBuilder() {
        if (tripleBuilder_ != null) {
          return tripleBuilder_.getMessageOrBuilder();
        } else {
          return triple_;
        }
      }
      /**
       * <code>required .Triple triple = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ProtobufJoinTree.Triple, ProtobufJoinTree.Triple.Builder, ProtobufJoinTree.TripleOrBuilder> 
          getTripleFieldBuilder() {
        if (tripleBuilder_ == null) {
          tripleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ProtobufJoinTree.Triple, ProtobufJoinTree.Triple.Builder, ProtobufJoinTree.TripleOrBuilder>(
                  triple_,
                  getParentForChildren(),
                  isClean());
          triple_ = null;
        }
        return tripleBuilder_;
      }

      // repeated .Node children = 2;
      private java.util.List<ProtobufJoinTree.Node> children_ =
        java.util.Collections.emptyList();
      private void ensureChildrenIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          children_ = new java.util.ArrayList<ProtobufJoinTree.Node>(children_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ProtobufJoinTree.Node, ProtobufJoinTree.Node.Builder, ProtobufJoinTree.NodeOrBuilder> childrenBuilder_;

      /**
       * <code>repeated .Node children = 2;</code>
       */
      public java.util.List<ProtobufJoinTree.Node> getChildrenList() {
        if (childrenBuilder_ == null) {
          return java.util.Collections.unmodifiableList(children_);
        } else {
          return childrenBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Node children = 2;</code>
       */
      public int getChildrenCount() {
        if (childrenBuilder_ == null) {
          return children_.size();
        } else {
          return childrenBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Node children = 2;</code>
       */
      public ProtobufJoinTree.Node getChildren(int index) {
        if (childrenBuilder_ == null) {
          return children_.get(index);
        } else {
          return childrenBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Node children = 2;</code>
       */
      public Builder setChildren(
          int index, ProtobufJoinTree.Node value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.set(index, value);
          onChanged();
        } else {
          childrenBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Node children = 2;</code>
       */
      public Builder setChildren(
          int index, ProtobufJoinTree.Node.Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.set(index, builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Node children = 2;</code>
       */
      public Builder addChildren(ProtobufJoinTree.Node value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.add(value);
          onChanged();
        } else {
          childrenBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Node children = 2;</code>
       */
      public Builder addChildren(
          int index, ProtobufJoinTree.Node value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.add(index, value);
          onChanged();
        } else {
          childrenBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Node children = 2;</code>
       */
      public Builder addChildren(
          ProtobufJoinTree.Node.Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.add(builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Node children = 2;</code>
       */
      public Builder addChildren(
          int index, ProtobufJoinTree.Node.Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.add(index, builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Node children = 2;</code>
       */
      public Builder addAllChildren(
          java.lang.Iterable<? extends ProtobufJoinTree.Node> values) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          super.addAll(values, children_);
          onChanged();
        } else {
          childrenBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Node children = 2;</code>
       */
      public Builder clearChildren() {
        if (childrenBuilder_ == null) {
          children_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          childrenBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Node children = 2;</code>
       */
      public Builder removeChildren(int index) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.remove(index);
          onChanged();
        } else {
          childrenBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Node children = 2;</code>
       */
      public ProtobufJoinTree.Node.Builder getChildrenBuilder(
          int index) {
        return getChildrenFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Node children = 2;</code>
       */
      public ProtobufJoinTree.NodeOrBuilder getChildrenOrBuilder(
          int index) {
        if (childrenBuilder_ == null) {
          return children_.get(index);  } else {
          return childrenBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Node children = 2;</code>
       */
      public java.util.List<? extends ProtobufJoinTree.NodeOrBuilder> 
           getChildrenOrBuilderList() {
        if (childrenBuilder_ != null) {
          return childrenBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(children_);
        }
      }
      /**
       * <code>repeated .Node children = 2;</code>
       */
      public ProtobufJoinTree.Node.Builder addChildrenBuilder() {
        return getChildrenFieldBuilder().addBuilder(
            ProtobufJoinTree.Node.getDefaultInstance());
      }
      /**
       * <code>repeated .Node children = 2;</code>
       */
      public ProtobufJoinTree.Node.Builder addChildrenBuilder(
          int index) {
        return getChildrenFieldBuilder().addBuilder(
            index, ProtobufJoinTree.Node.getDefaultInstance());
      }
      /**
       * <code>repeated .Node children = 2;</code>
       */
      public java.util.List<ProtobufJoinTree.Node.Builder> 
           getChildrenBuilderList() {
        return getChildrenFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ProtobufJoinTree.Node, ProtobufJoinTree.Node.Builder, ProtobufJoinTree.NodeOrBuilder> 
          getChildrenFieldBuilder() {
        if (childrenBuilder_ == null) {
          childrenBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ProtobufJoinTree.Node, ProtobufJoinTree.Node.Builder, ProtobufJoinTree.NodeOrBuilder>(
                  children_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          children_ = null;
        }
        return childrenBuilder_;
      }

      // repeated string projection = 3;
      private com.google.protobuf.LazyStringList projection_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureProjectionIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          projection_ = new com.google.protobuf.LazyStringArrayList(projection_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string projection = 3;</code>
       */
      public java.util.List<java.lang.String>
          getProjectionList() {
        return java.util.Collections.unmodifiableList(projection_);
      }
      /**
       * <code>repeated string projection = 3;</code>
       */
      public int getProjectionCount() {
        return projection_.size();
      }
      /**
       * <code>repeated string projection = 3;</code>
       */
      public java.lang.String getProjection(int index) {
        return projection_.get(index);
      }
      /**
       * <code>repeated string projection = 3;</code>
       */
      public com.google.protobuf.ByteString
          getProjectionBytes(int index) {
        return projection_.getByteString(index);
      }
      /**
       * <code>repeated string projection = 3;</code>
       */
      public Builder setProjection(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProjectionIsMutable();
        projection_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string projection = 3;</code>
       */
      public Builder addProjection(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProjectionIsMutable();
        projection_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string projection = 3;</code>
       */
      public Builder addAllProjection(
          java.lang.Iterable<java.lang.String> values) {
        ensureProjectionIsMutable();
        super.addAll(values, projection_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string projection = 3;</code>
       */
      public Builder clearProjection() {
        projection_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string projection = 3;</code>
       */
      public Builder addProjectionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProjectionIsMutable();
        projection_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Node)
    }

    static {
      defaultInstance = new Node(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Node)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Triple_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Triple_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Triple_Element_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Triple_Element_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Node_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Node_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016JoinTree.proto\032\013Stats.proto\"\355\001\n\006Triple" +
      "\022 \n\007subject\030\001 \002(\0132\017.Triple.Element\022\"\n\tpr" +
      "edicate\030\002 \002(\0132\017.Triple.Element\022\037\n\006object" +
      "\030\003 \002(\0132\017.Triple.Element\022\025\n\005stats\030\004 \001(\0132\006" +
      ".Table\032:\n\007Element\022\014\n\004name\030\001 \002(\t\022!\n\004type\030" +
      "\002 \002(\0162\023.Triple.ElementType\")\n\013ElementTyp" +
      "e\022\014\n\010VARIABLE\020\000\022\014\n\010CONSTANT\020\001\"L\n\004Node\022\027\n" +
      "\006triple\030\001 \002(\0132\007.Triple\022\027\n\010children\030\002 \003(\013" +
      "2\005.Node\022\022\n\nprojection\030\003 \003(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Triple_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Triple_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Triple_descriptor,
              new java.lang.String[] { "Subject", "Predicate", "Object", "Stats", });
          internal_static_Triple_Element_descriptor =
            internal_static_Triple_descriptor.getNestedTypes().get(0);
          internal_static_Triple_Element_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Triple_Element_descriptor,
              new java.lang.String[] { "Name", "Type", });
          internal_static_Node_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Node_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Node_descriptor,
              new java.lang.String[] { "Triple", "Children", "Projection", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ProtobufStats.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
